org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=picktool
mod.name=Pick Tool
mod.group=me.pajic
mod.version=1.1.1
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Pick block while holding a tool to swap to the effective tool for that block
mod.sources_url=https://github.com/pajicadvance/pick-tool
mod.homepage_url=https://modrinth.com/mod/pick-tool
mod.issues_url=https://github.com/pajicadvance/pick-tool/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=xxJXgVn0
publish.curseforge=1499141
publish.github=false
